### PR TITLE
Cleanup WIC file

### PR DESCRIPTION
**Pull request by JPEWdev**
Makes several improvements to the kickstart file

### CODE REVIEW

**Comment by alistair23** [comment]
Thanks for the PR!

I have manually applied three patches, this commit breaks the boot for me: https://github.com/alistair23/meta-pine64/pull/12/commits/bf6fdedf44cd5705ae1b9c183d05f0c60ced9923

Unfortunately I don't have UART on the board so it's hard to debug why it's failing.

**Comment by JPEWdev** [comment]
Hmm, that's unfortunate. I've looked over the change several times, and I can't see where the problem might be.... is there any way you could get a serial port attached? Otherwise I'm not sure what to do

**Comment by alistair23** [comment]
Does it work on your board?

I have tried before, it seems like there is a hardware issue with my board and I never get anything from the UART. It is a huge pain.

**Comment by JPEWdev** [comment]
Ya, not having UART is really annoying. Mine works fine with a USB-Serial converter attached to the 6 pin header in the Pine H64: [PineH64 USB Serial](https://photos.app.goo.gl/6sNHbA7QMY3ZRLHx8)

For reference, here is the minicom config file I use:
```
pu port     /dev/tty-pineh64
pu baudrate 115200
pu rtscts   no
pu xonxoff  no
```

**Comment by alistair23** [comment]
Sorry, I haven't gotten the UART to work still

**Comment by JPEWdev** [comment]
> Sorry, I haven't gotten the UART to work still

Hmm, that's too bad. I think I might split apart the wic files then so that the I can use this version on the pineh64 and the other can stay as they are.... unfortunate, but I don't really know of a better way to do it

**Comment by JPEWdev** [comment]
Ok I updated #11 to add support for the pineh64 without changing the wks file for the other board. Hopefully that one will work.

**Comment by alistair23** [comment]
Thanks, I merged #11

**Pull request closed without merging**
